### ISSUE TITLE
Strategy for multithreading

### ISSUE THREAD

**Issue by maaaaz** [fox-it/BloodHound.py#5]
Hello there,

This tool looks promising but unfortunately it will only be usable on real domains only if it is fast enough, that is to say **multithreaded.**
Bloodhound devs went from PowerShell to C# for the ingestor (only) to allow fast data collection.

Do you already know what will be your strategy for multithreading ?
There are several possibilities with Python but it depends a lot on the version (and you depend on `impacket` 2.7 code):
* 2+ `asyncore` builtin module is known to have some bugs/limitations
* 2.7+ `twisted` is [renowned](https://pypi.python.org/pypi/Twisted)
* 3.2+ `concurrent.futures` is [great](https://julien.danjou.info/scaling-python-application-threads/), maybe the [unofficial 2+ backport](https://github.com/python/cpython/blob/2.7/Lib/asyncore.py) does the job ?
* 3.6+ `asyncio` is [shiny](https://julien.danjou.info/scaling-python-application-asyncio/) but 3.6+ only...

Cheers.

**Comment by dirkjanm** [comment]
Heya, thanks for reaching out!

At the moment I'm not sure yet of the strategy, I might go for Twisted, which I used for example with mitm6, or just manual threading to start with. Since most of the tasks are pretty straightforward and almost all run by external libraries (such as impacket), using a framework might not be the best solution since it will just complicate things and introduce extra dependencies.
Threading is on the schedule as one of the first things though, so definitely working on it!

**Comment by dirkjanm** [comment]
I've discussed this with @mwgielen and we're going to start with manual threading and workers for now. If the project gets more complex we can always see if using a framework adds advantages.

**Comment by mwgielen** [comment]
Fixed in 0cd78d1af318dcd179785a23244434348a170810

**Comment by maaaaz** [comment]
Great ! I'll try to test it!

**Comment by dirkjanm** [comment]
This is now released as part of 0.3.0 in master. If there are any bugs, please open a new issue.
