### ISSUE TITLE
GPO based collection method

### ISSUE THREAD

**Issue by h-betz** [fox-it/BloodHound.py#56]
I saw under the limitations - https://github.com/fox-it/BloodHound.py#limitations - that GPO based collection methods are not supported. What are the blockers preventing these methods from being implemented? Just trying to get an idea of whether or not its worth forking the repo and implementing the solutions for the GPO based collection. My team and I are looking for ways to automate the BloodHound process and this seems to be the best solution so far though the limitations mentioned are serious blockers on our end.

**Comment by dirkjanm** [comment]
The primary blocker is time, there are quite some things that need to be added in order to support this.

Including:
- OU gathering / parsing / output (including integration in the current gathering/output processing)
- GPO collection / reading / parsing, which is not too complex I imagine but I'm simply not an expert on GPO's so it's something I'd have to dig in to

Also information collected by BloodHounds GPO methods is ultimately not completely reliable since only limited GPO options are parsed and they don't give certainty that the GPO actually applies to the computer. Not really a stopper but it is something to take into account when focusing efforts.

**Comment by h-betz** [comment]
Great, thank you!
